background_b: 255
background_g: 86
background_r: 160
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_nathan_inspiron_5547__41133: 'http://nathan-Inspiron-5547:41133/'}
rosversion: '1.12.14

  '
run_id: 98bb8354-3b62-11e9-9426-a0886966c286
